### ISSUE TITLE
Highlighting problem for currently playing track

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#22] opened 2017-02-24 01:32 UTC
New issue in either b2.20 or 2.10 (not sure, just know that it wasn't a problem in 2.0).

Platform: Fedora 24, Gnome 3
Install Method: AppImage

In the new beta, for some reason the currently playing track when playing an album is "whitewashed" out.  As a result, it's fairly difficult to tell which track is currrently playing.

See screencap; in this picture the track "French Affair" is playing, but the only way to tell is that the track number is invisible.   Also there's a seperate issue that the track name only displays on mouseover in the bottom bar, but I'll file another issue for that.

In beta2.0, the current track was highlighted in a visible color.  Not sure what happened.

**Comment by jberkus** [comment] 2017-02-24 01:34
![screenshot from 2017-02-23 17-28-28](https://cloud.githubusercontent.com/assets/115146/23286670/49deb9a2-f9ee-11e6-9cc6-460c9a449863.png)

**Comment by aprile** [comment] 2017-02-24 12:01
This looks like a bug, and I've actually seen it before but I am having trouble reproducing it reliably. I bet if you restart the app, the playing graphic will show... Thanks for bringing it to our attention though, once we're able to reproduce we will be able to fix this. As far as I know it happens pretty rarely.

**Comment by jberkus** [comment] 2017-02-24 21:47
Restarting Voltra did not change anything.  I can't test restarting my desktop right now; once I'm able to I'll test and report back.

**Comment by heapwolf** [comment] 2017-02-24 21:53
@jberkus i noticed this too. It *might* be fixed in this next release. I realized today that I was using  `ByteTimeDomainData` instead of `ByteFrequencyData` to draw the visualization, in many cases that data would be totally out of range for the code that does the calculation, causing it to appear blank.

**Comment by aprile** [comment] 2017-03-10 19:58
We have fixed this issue.

**Closed as completed by aprile** 2017-03-10 19:58 UTC
Labels: Bug

**Comment by jberkus** [comment] 2017-03-13 22:52
Thanks, I'll update with the next release.

**Comment by jberkus** [comment] 2017-04-17 21:05
Confirmed fixed in 2.5.12.
