### ISSUE TITLE
Error when refreshing Voltra from Chromium Inspector

### ISSUE THREAD

**Issue by jordikroon** [voltraco/beta#11] opened 2016-10-31 22:38 UTC
**Issue:**
Error when refreshing Voltra from Chromium Inspector

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: bundle.js:478:289.
    at AutoUpdater.callIntoRenderer (/Applications/Voltra.app/Contents/Resources/electron.asar/browser/rpc-server.js:192:19)
    at emitOne (events.js:101:20)
    at AutoUpdater.emit (events.js:188:7)
```

**Steps to reproduce:**
 - Open Voltra
 - Press Ctrl Cmd i to open the Chromium Inspector
 - Focus on the Chromium Inspector
 - Fire Ctrl-R (Refresh)

**Comment by heapwolf** [comment] 2016-10-31 22:41
You have attempted to refresh the page after the main process has been restarted, thus the render processes is detached from the underlying node/main process -- this is a result of how electron is architected. Closing for now since its not a bug, but of course any further discussion is totally welcome :)

**Closed as completed by heapwolf** 2016-10-31 22:41 UTC
